### PR TITLE
youtube-dl: WARNING: --title is deprecated

### LINKED ISSUE #100: youtube-dl: WARNING: --title is deprecated. Use -o "%(title)s-%(id)s.%(ext)s" instead.
`WARNING: --title is deprecated. Use -o "%(title)s-%(id)s.%(ext)s" instead.`

### PR DESCRIPTION
**Pull request by cyaniventer**
fixes #100

### CODE REVIEW

**Comment by Mikaela** [comment]
Thanks, could you also update zshrc?

I am not sure if I will be able to merge today.

**Comment by cyaniventer** [comment]
updated zshrc

**Comment by Mikaela** [comment]
Could you also merge the three commits into one? I think you can use `git rebase -i HEAD~3` [source](https://stackoverflow.com/a/37268543)

**Comment by cyaniventer** [comment]
ah! I just learned how to do that rebase thing but I don't understand branches and couldn't do that for a different branch. I'll try to fix this tommorow.

**Pull request closed without merging**
